name: 🥖 Daily Starter Reminder

on:
  schedule:
    - cron: '0 20 * * *'  # Runs at 08:00 UTC daily
  workflow_dispatch:    # optional: manual trigger via GitHub UI

jobs:
  starter-check:
    runs-on: ubuntu-latest

    env:
      ENV_NAME: ${{ vars.ENV_NAME }}
      KEY_FILE_NAME: ${{ secrets.KEY_FILE_NAME }}
      FEEDING_TRACKER: ${{ secrets.FEEDING_TRACKER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests python-dotenv 

      - name: Run starter check
        run: python feeding_gsheet.py